(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"KaitlinCallingCard_atlas_1", frames: [[402,0,488,107],[0,402,827,71],[0,0,400,400]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_2 = function() {
	this.initialize(ss["KaitlinCallingCard_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_1 = function() {
	this.initialize(ss["KaitlinCallingCard_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.photo_20210215_200610 = function() {
	this.initialize(ss["KaitlinCallingCard_atlas_1"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.PinkBtn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#333333").ss(6,1,1).p("AHoAAQAADKiPCPQiPCPjKAAQjJAAiPiPQiPiPAAjKQAAjJCPiPQCPiPDJAAQDKAACPCPQCPCPAADJg");
	this.shape.setTransform(48.75,48.75);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D9ABAB").s().p("AlYFYQiOiOgBjKQABjJCOiPQCPiODJgBQDKABCOCOQCPCPAADJQAADKiPCOQiOCPjKAAQjJAAiPiPg");
	this.shape_1.setTransform(48.75,48.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3,-3,103.5,103.5);


(lib.PhotoAnimation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.photo_20210215_200610();
	this.instance.setTransform(0,0,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,200,200);


(lib.linkbar = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(153,153,153,0.796)").s().p("ABWJCIkYgGQj6gHkwgNIjBgHImFgMQhEgCh2gGIgIgBIjOgQIABAQIgRgRIgIAAIAAgIIgFgFIABANIgNAAIANANIAAAEIgRgRIgCAAIAAgCIgRgSIADAAIgDgEIARAAIAAAEIALAAIgEgFIgHABIAAgIIgRgRIARAAIgBgtIgDAjIABknIAAjXIAAgMIABAEIABArQACBgABARIAAhBIADAMQgBgPAAgQIABgZQAHDWAGEKIAEAAIgJmiIgWotIASD2IABAYIAkLAIGygGIIFABINuALIE5AIQDSAFByACIF7AGQAeACAfAAIAzgBQASgCgEgDIHoASIAMrXIABkZIjjABItNALIhQAFQgzADgYAAQiZgCiDABIojAJQh4ACiXABQj4gBiNgDQgJACgYAAIhugDIgrgCIiigHIh6gHIjhgLIhQgFIgagBICVAFIEcAIIHwAHQCvABgFgCQgIgBh7gBIkJgEIi+gEIDmgCQCpgBDPgDIFygIIGHgJQBGgDguAAQhlAAknAGIkgAGIlhAGIjsABIjzgBIAxgBICdgDIBCgCICngGIC9gFIB5gFICDgDIUmgMIkyAKQjXAHhnABQB9ADBugCQBDgBCFgGIDNgFIB+AAIEsAFImJgPIBjABIMwAOIACCKIABiMIgWgBQh2AAiWgEIrfgOIlfgDQjAgChhgFIgoACIgTgBQh1ABhagEICuAAQChgHDCAAQCXAADbAHIGpAQIJgAOIAAAWIgBCTIAGHRIAAg5IAOIOIgCgiIgDgaIABA+IAEgBIABAEIhWADIBNgGIotAIQi2AAj+gCImzgGQjYgEjZgFQiZgErHgVIhIgCQlMgJj2gEICMAFIDQAIIBeAEQHeASDmAIQDCAGCfAEIFgAGIIYAGIIdgCIFugIQhhAFhaABIkkAIQiBACihABgA2VHyQFiAEG6AMIGNAKISmAeIDIACIDHABQCygBDegDIAegBIgKrdIAAg7QgBCKAACcIAEHsIgXAAQjpABiqgCIlqgKQg1gBhJACIm4gMIhFgCIAeACQERASEDACQlzAAmggPIhugFIkIgLIl7gQQkPgDjJAAQhyAAjaAEgA7/HnIAOAOIAAgOgA7fHnIAEAAIAAgFIgEAAIAAAFgA7CHhIAAAFIFggGQgYgEg9AAgAWKodIFcAGIAELpIAChVIgClGIgBlCIAAgQIgQAAQhzAAikgCgAbgiZIABArIAAmlIlBABQilAAheACIJCgBgA7eIIIAAgNIAEAAIAAARgA8CH6IARABIAAARgAbyk7IAAjQIAAgYIi1gDQhugBhugFIiLgHICJAEIDWAFIDAAEIAAAbIgCDRIAABOg");
	this.shape.setTransform(204.6108,52.425,1.1395,1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(204,204,204,0.6)").s().p("AGaIMIgegCIBGACgAjRIMImNgKQm5gMljgEQDagEBzAAQDIAAEPADIF7AQIEJALgAy8IMIjQgIIiNgFQD2AEFMAJgA7nIMIAAgSIARASIAAgRIACAAIARARIAAgEIAEAEIAAgRIgEAAIAAANIgNgNIANAAIgBgNIAFAFIAAAIIAJAAIAQARIAAgQIDNAQgA7nH6IAAgTIARASIAAACIgRgBgA7jHnIANAAIAAAOgAT0HfQAEADgTACIgyABQggAAgdgCIl8gGQhygCjRgFIk5gIItvgLIoEgBImzAGIgjrAIgCgYIgSj2IAXItIAIGiIgEAAQgGkKgHjWIAAAZQgBAQABAPIgDgMIABBBQgCgRgChgIgBgrIgBgEIAAAMIAADXIAAEnIACgjIABAtIgRAAIARARIAAAIIAHgBIAEAFIgLAAIAAgEIgRAAIAAgZIAAvVIKkAAIhCACIicADIgyABIDzABIDsgBIFigGIEMAAIlxAIQjQADipABIjmACIC+AEIEKAEQB6ABAIABQAGACiwgBInwgHIkbgIIiWgFIAaABIBQAFIDhALIB6AHICiAHIArACIBvADQAXAAAJgCQCNADD4ABQCXgBB5gCIIjgJQCCgBCZACQAYAAAzgDIBQgFINNgLIDjgBIgBEZIgMLXInngSgA7nHnIAAgEIAEAEgA7EHnIAAgFIAFAAIAAAFgA6nHhIELgFQA9AAAZAEIlhAGg");
	this.shape_1.setTransform(201.5058,52.425,1.1395,1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.linkbar, new cjs.Rectangle(0,-5.9,409.2,116.7), null);


(lib.Start_btn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.PinkBtn();
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Start_btn, new cjs.Rectangle(-3,-3,103.5,103.5), null);


// stage content:
(lib.personal_landing_HTML5Canvas = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Start
	this.instance = new lib.Start_btn();
	this.instance.setTransform(125.1,315,1,1,0,0,0,48.8,48.8);

	this.instance_1 = new lib.PinkBtn();
	this.instance_1.setTransform(76.3,266.2);
	new cjs.ButtonHelper(this.instance_1, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},4).to({state:[]},55).wait(1));

	// linkbar
	this.instance_2 = new lib.linkbar();
	this.instance_2.setTransform(1044.4,315.55,1.3317,1,0,0,0,202.3,52.4);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(39).to({_off:false},0).wait(1).to({regX:204.6,x:997.7},0).wait(1).to({x:948},0).wait(1).to({x:898.3},0).wait(1).to({x:848.6},0).wait(1).to({x:798.9},0).wait(1).to({x:749.2},0).wait(1).to({x:699.5},0).wait(1).to({x:649.8},0).wait(1).to({x:600.1},0).wait(1).to({x:550.4},0).wait(10).to({regX:202.3,scaleX:1.3713,x:555.4,y:327.55},0).wait(1));

	// grad
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(8,8,8,0.973)","#000000","rgba(7,7,7,0.976)","rgba(16,16,16,0.925)","rgba(30,30,30,0.843)","rgba(32,32,32,0.831)","rgba(29,29,29,0.847)","rgba(34,34,34,0.098)","rgba(61,61,61,0.784)","rgba(241,241,241,0.149)","rgba(116,116,116,0.588)","rgba(30,30,30,0.098)"],[0,0,0.024,0.341,0.706,0.89,0.894,1,1,1,1,1],-0.1,88.7,-0.1,-89).s().p("EhABAN5IAA7xMCADAAAIAAbxg");
	this.shape.setTransform(379.2,331.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(60));

	// quote
	this.instance_3 = new lib.CachedBmp_1();
	this.instance_3.setTransform(278,117,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(60));

	// name
	this.instance_4 = new lib.CachedBmp_2();
	this.instance_4.setTransform(363.4,59,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(60));

	// slash
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(204,204,204,0.796)").s().p("AAyCWIgIgDIgBgBIgBgBIgWgRIgCgCIgBgBIgPgOQgLgLgEgKIgCAQIAAAFIgMAoIAEgeQAEgggCABIgGAsIAAguQgBgUgCgIIgCgNQgBgCAAAAQAAgBAAAAQAAgBAAABQAAAAAAABIAFA6IgBAeIgDgdIgEgRQgBgFgBgOIgBgPIgKgvQAGAKAEAIQAFAMgBAIQADgIgCgHQgBgDgEgJIgFgLQgDgIAAgHIgBgJIACgJIAAgHIgBgYIABgRIACgJIADgJQgBACgGACIAAADIgCABIgBAEIgDAIIgBAOIACAcQgBACADAFIADAGQAAAFgCAHIgDAKQgDgLgBgNIgBgTIgBgCIAAgEIgDgFIgEgHIAAASIAAAGQAAAHAEAOIAHAVIAEAUQABALgCAFIABADIAAABQABAFgBAGIgCgKQgIgVgDgUIgFgrQgCgDABgDIABgDIABgDQABgJAAgDQgCgJABgIIABgJIABgHIAAgCIAAgBIABgCIgDAIIgFALIAAAgIAAADIAAACQABASgDAHIgFgaIgBgCIABgDIAAgEIACgJIAFgSIABgLIAFgQIAGgMIABgCIADgEIAAAAIAAgBIABAAIABgDIABgBIABgBIACgCIAGgGIAAAAIAAAAIAGgDIAAgBIABgBIAFgCIACgCIAJgDIABAAIAPgCQACgBADABIAFAAIAJACIACABIACAAIAFABIABABIAFADIACABIABABIAEACIABABIAAAAIABABIACABIADAEIABAAIABABIAEADIABAAIABADIABABIABAAIABACIABABIAAAAIACABIAAABIABABIABACIABABIABACIAAACIADAFIABACIABABIABABIABABIAAACIAMAcQADAIACAJIACARQAAASgGARIgSAtIgCAMQgEANgFAKIgNAPIAAAFIACAEIABgCIAAACIAAABIAAABQACAFABAGIADAMQAAAAAAABQAAAAgBAAQAAgBAAAAQAAgBgBAAIgEgGIAAABIAAACIgCAAIAAAEIgCgEIgCgBIgVgkIgBgCIgDgGQgCACgBAEIACADIAAABIAGAIIAEAIIACACIAJARIARAVIABABIAAAAIABABIACABIAEADIABABIgEgCgAATiMIAAABIABAAIAAAAIABAAIADACIABABIAAAAIACABIACACIABABIABAAIAFAEIABABIABACIACACIAAABIABABIAAABIADADIABABIAAABIABABIABABIAAABIABABIAAABIAHAQIAFAZIABANIAAAbIgDAbIgOAzIgFAaIgDATIAFgRIAHgSIAWhAIAEgZIAAgNIgBgDIAAgDIgEgVIgHgaIgBgBIgCgEIAAgCIgBAAIgGgOIgBAAIAAgCIgBgBIgEgGIgGgFIgCgCIgCgBIgCgCIgIgDIgCAAIgGgCIgCAAgAAogtIAAAGIAAAHIgCALIgFAMIgTAuIABATIABADIABADQACAGAFALQAAgPADgOIAShLIADggIgBgQIgEgUIgBgBIgBgDIAAgCIgBgBIgBgCIAAgCIgBgBIgEgHIgCgCIAAAAIgBgCIgBgBIAAgBIAAAAIAAAAIgDgDIgCAAIgBgCIgBAAIAAgBIgBAAIgBgCIgBAAIgBgBIgEgCIgBAAIgDgCIgJgCIgCAAIgEgBIgJABIgIACIgFACIgCAAIgDACIgBABIgBABIgCACIgCABIgFAFIgBACIgDACIgCACIAAABIgBABIgBADIgBACIgBAAIAAABIgBACIAAAAIgBABIgBACIgDAIIgGASIgCARIAOgfIAHgOIABgBIABgBIABAAIAAgBIACgDIABgBIAAgBIADgDIABgBIACgBIABgBIABgBIAAAAIAEgDIABgBIACgBIABAAIABgBIABAAIAEgBIABAAIABgBIACAAIACAAIADgBIAIABIAHACIADABQAGAEACACIAEAEIAAABIACADIAEAFIAAABIABADIAAAAIACAKIAAADIAAACQABAGgCAEIgDAJIABAGQAAADACAEIgGAeQAIgIADgKQAEgJgBgJIACALgAgfgMIgCgkIgBAAIABgFIAAgFIACgUIABgHIAAAAIAFgKIABgBIADgEIAAgBIABAAIABgBIAIgEIADgBIADAAQAAAAAAAAQAAAAABAAQAAAAAAAAQABAAAAAAIACAAIABABIABAAIAAAAIACABIACABIAAAAIABAAIAAABIAGADIAJAMIgGgJIgCgCIAAgBIgEgDIgBgBIgBgBIgBAAIgDgBIAAgBIgBgBIgBAAIgBAAIgCgBIgFAAIgFABIgCACIgBAAIgDACIgBABIgBABIgBAAIgBABIgBABIAAACIgBABIAAABIgBABIgBABIgBABIgBABIAAACIgBAAIAAABIgEAMIgCAKQgDAKAAALQAAAJABAJIAGAQgAgdhZIgBAEIgBAEgAgehVg");
	this.shape_1.setTransform(366.85,198.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(204,204,204,0.796)").s().p("AgXANIgEACIgBAAIgCAAIgCAAIgBAAIgFgBIAFgBIAAgCIgDAAIgIAAIgEABIgDAAIgDABIgBAAIgCABIgCABIgBAAIABgBIACgCIAEgBIADgCIgFABIACgCIgCABIgIgJIgCAAIgBABIgBAAIAAABIAAABIgBAAIAAABIgBgCIABgCIABAAIACgBIABgBIACgDIACgBIABgBIAAAAIADgBIADgBIAIgDIAEgBIADgCIABgBIADAAIABgBIAAAFIgBADIgBADQAAADABADIAAAAIACgBIABAAIAAABIAAADIAIABIgBgIIABAAIADgBIABAAIgBgMIADAAIAEgBIABAAIABgBIADAAIAEAAIAEAAIABAAIAGgBIACAAIAOAAIAAACIgBADIgDAAIgKADIgDABIgBAAIABAAIgBAAIAAAAIgBAAIgCAAIgBAAIgFAAIAEACIgDgBIgFABIgDABIAAAAIgBANIABAAIADABIgCABIgBAAIgBAAIgFABIAAAAIABABIABAAIACAAIAFABIAEABIADAAIABAAIgIABIgGABIgBAAIABABQAAAEgCAHIgDAKQgDgKgBgMgAg6ALIABAAIgBAAIgBABIABgBgAg3AKIAAAAIgBAAIgBABIACgBgAAdgPIgBAAIgBAAIABgEIAAgBIAOAAIgEgCIgJgEIgCAAIgFgCIgBAAIgBgGIAAAAIAGAAIAGAAIACAAIAFAAIAMACIADABIACACIAEgBIACgBIADABIACABIgHAAIAAAAIgBACIABABIAKADIgSADIgEAAIgGAAIAPAIgAgfgWIADAFIAAAAIgDAAgABCgdIAAAAIgBgBIABAAIAAABIABAAgAAQgeIgLgEIADABIALgBIABAAIAAAAIAAABIgCAEIgCgBg");
	this.shape_2.setTransform(365.775,195.325);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(204,204,204,0.796)").s().p("Ah8AaIAEgCIAHgEIAJgDIgCAAIgIADIgDABIgEADIgDABIACgBIADgCIACgCIADAAIADgCIgFACIgMgIIgGAFIAAABIgCACIgCACIAAABIAAgDIABgCIADgCIACgDIADgCIAEgDIAEgDIABAAIABgBIAGgCIAFgCIAQgDIAJgCIAEgCIgBACIgBADIAAACQAAABAAABQAAAAAAABQAAAAAAABQAAAAAAABIADgBIAAAAIAFgCIACAAIAFgBIgBgKIAIAAIACAAIAHAAIAGAAIAIAAIAIAAIADAAIACAAIAFAAIAEAAIAGAAIAJABIAGAAIgBABIgCALIgDAFIgFAIIgEgIQgEgIgCgHIAAAAIgIABIgDAAIgGAAIgDACIgDABIgMABIgGABIgEAAIAAAFIAAACIAKAAIALABIAGABIAGAAIgCABIgDAAIgOABIgNACIAGABIAGAAIACAAIAEgBIABAAIAPABIAHAAIAHABIACAAIAAABIgQAAIgSABIgFgBIgEABIgKABIAAAAIACgGIAAgFIgHABIgEAAIgHAAIABAHIAGAAIAAACIAAABIAAABIgDAAIgCAAIAAgBIgEABIAAgDIgQACIgHABIgHABIgFADIgDABIgEACIgEACIgCABIADgDgAgQgHIACAAIAAAAIAAAAIAAAAIgCAAgAh9AaIABgBIgBABgAhSATIADAAIAAAAIgDAAgAg/APIACAAIgCAAIAAAAgAA8gEIAAAAIgBgGIAAgBIgBgDIgCgKIAGABIAIACIAaAFIAFACIAHADIADAAIgQABIADABIAkAHIAFAAIAAABIgnABIgFAAIAMADgAAZgHIADAAIABgIIgBgIIgCAAIgOgDIABgBIAgABIADABIABAIIgCgBIgIgCIABAGIAAAHIAAABgAALgIQAAgBAGABIACAAIAAABIgIAAgAAUgIIAFABIgFAAIAAgBgAB+gIIAAgBIABABgABwgKIABAAIgCgBIAFAAIAIACIACAAgAB8gJIgBgBIADABgAADgcIACAAIAEABIACAAIAAABg");
	this.shape_3.setTransform(373.025,194.45);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(204,204,204,0.796)").s().p("Ai7AdIAGgEIAKgFIALgEIgMAEIgGADIgGADIgEADIgBAAIAAAAIABAAIADgDIAEgCIAFgCIAAAAIgPgGIgKAJIgCACIAAABIgDADIAAAAIAAgCIACgEIAEgDIAEgEIAEgCIAFgFIAGgDIACgBIABgBIAJgDIAIgDIAYgEIANgDIgBADIgBADIAAACIABABIAAACIADgBIAHAAIAAAKIgFABIgBgDIgDAAIgUAEIgKABIgLADIgIAEIgEACIgGACIgGAEIgDACIAFgEgAh7APIADgBIAAABIgDAAgAhrAOIgCgCIAAgCIgBAAIAFgBIAAgBIABgLIgHABIgBAAIgEABIAAgCIAAgDIgBgDIABAAIAEgBIABAAIAGgBIABAAIAUAAIAJAAIAKABIAKAAIACAAIADAAIADAAIAAAAIAEAFIAEAEIgCAJIACAAIACAAIAFAAIABABIgHAAIgBAAIgCAAIgYABIgHAAIgHAAIgOADIgJABIgEAAIgBAAgACUAJIACAAIADAAIAFACgAgTAKIABgBIABAAIACAAIABABIgFAAgABlgJQgRgFgPgEIgQgEIgRgEIghgGIAIABIA2AEIAZAFIANADIAmAJIAJACIAJAFIAIACIgCgBIAHABIAMABIAFAAIgCAAIgPgBIgfAAIAEABIA3AIIAHAAIg2ABgACJAIIhvgOQgJgCABACIgJgBIgBgEIAlABIBnATIgLgBgAgWAIIABgRIAIAAIgHARIgCAAgAC4AAIgCAAIADAAIgBAAgAgqgKIACAAIACAAIABgBIgBAAIAIAAIAAABIgDAAIgFAAIgBAHIgDgHgAgKgIIAAgFIABAAIAHABIACAAIAAACIgCACIgIAAgAgagKIgCAAIgBgBIAFAAIADAAIAAACIgFgBgAAAgLIAAAAIABgBIACABIgDAAIAAAAgAgVgLIAAgBIgGgBIAGAAIAAABIAFABIgFAAg");
	this.shape_4.setTransform(380.125,194.55);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(204,204,204,0.796)").s().p("AkSAlIADgFIAFgFIAEgFIAHgEIAGgFIAIgEIADgBIACgCIAKgDIAMgDQAQgFAQgDIAMgCIgBAEIAAACIAEgBIAAgFIACgBIADAAIAAAAIAAADIABABIgCAAIgEACIAAAAIAAADIgDAAIAAAAIAAAAIABAIIgZADIgNADIgOAFIgMAEIgEACIgIAEIgIAFIgEADIAGgFIAIgFIANgGIAHgDIgFACIgHADIgDACIgIAEIgGADIAEgCIAFgEIAHgDIgSgDIgIAGIgJAKIgCAEIgBAAgAj9AfIABgBIgCACIABgBgAEKASIhDgBIgQgBIiVgVQgLgDABADIgUgDIgTgCIgBAAIgTgCIAAAAIAEgGIgBAAIABgBIABgBIgJgBIAKAAIAPABIAIABIACAAIAGABIgDAAIAGAAIA2AEICXAfIhNgZIgrgNIgVgFIgXgEIgsgHIAMAAIBHAHQASADAQAEIAQAEIAzANIAMAEIANAFIAKACIgCgBIAeAFQABAAAAAAQAAAAAAAAQAAAAgBAAQAAAAgBAAIgEgBIgBABIgPgDIgpgCIAFACIBLALIAJABIgIAAIgBAAgAimAJIABAAIAAAAIgBAAgAiaAJIAAgCIACgBIABgDIAAAAIAAgFIAAgBIgGAAIAAgFIAAgEIACgBIAEAAIAEgBIAJgBIAaAAIADAAIAFAAIAQgCIAHAAIABAAIABAAIABAEIgCAAIgCAGIgGAAIgBAFIAGgBIAGAAIAAACIgBABIgBACIgHAAIgCAAIgCAAIgIAAIgJAAIgSADIgMACIgNABIgDABIgBAAgAgiACIgHAAIgDAAIACgCIABAAIACAAIAHABIAHAAIADABIABABIgNgBgAg5ACIgCgCIAFAAIAEAAIAAAAIAAACIgDAAIgCAAIgCAAgAhIAAIAAgDIAAgDIABgHIAAgCIACACIAFAIIACABIABACIAAACIgLAAgAg9gFIAEAAIgEABIAAgBgAg2gMIgHAAIAAgGIAGgBIAEAAIABAFIAAACIgEAAg");
	this.shape_5.setTransform(387.25,194.8167);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(204,204,204,0.796)").s().p("AlXArIAFgGIAFgGIAHgGIAIgFIAHgGIALgFIADgCIACgBIAOgFIAOgDQAUgGAVgDIALgDIgBACIAAABIAEgBIAAADIgCAAIgBAAIAAAAIAAABIABAIIgdADIgRAEIgOAFIgJADIgIAEIgFACIAIgEIADgCIgLAFIAAAAIgDABIgJAGIgIAFIgGAEIALgIIAHgFIAHgDIgTAAIgKAHIgHAGIgBAAIgDAGIgBAAIgEAFIAAABgAk6AfIAJgGIAHgDIgJAFIgKAGIADgCgAEpAaIgwgBIgVgCIi5gcQgNgEAAADIgZgDIgYgDIgPgCIgBABIgJAFIgBABIAMABIAEABIACABIgWgBIgRAAIACgDIgEAAIgEAAIgGgDIgCgCIgHABIgDAAIgDgDIgBgBIAAgBIAHAAIAVACIAIgBIAHgIIAEgDIAAgBIABgBIgEgBIAEAAIAaABIABAAIAMACIAIABIgEABIAIAAIB1APICKAfIhegeQgegJgYgGIgbgGIgbgFIg5gJIAPABIBZAKQAWADAVAFIAVAFIBAASIANADIAQAHIANADIgDgBIAnAHIgDAAIgEgBIAAAAIAEABIhLgGIAHACIBcANIALAAIguABgAjOABIAAABIgDAAIADgBgAjFgCIAAgBIABgFIAAgDIgGABIAAgEIAFgCIAAAAIAEgBIADAAIAcgEIAQgCIAIAAIABADIAAABIAIAAIgBAEIgCAAIgFAAIgBAFIAGAAIAFgBIAGAAIAAgFIgGABIAAgBIgBgDIAEAAIADAAIAAADIAJAAIAAAEIALAAIAAADIAAADIAAABIgJAAIgBAAIgLgBIgBAAIgFABIABgCIAAgBIgGAAIgCADIgEAAIgSADIgPACIgQABIgKAAgAhEgFIgPAAIgEgEIAPABIADACIADABIgCAAgAjPgPIABAAIAEAAIAAABIgCAAIgDABgAjKgOIAAAAgAhngQIgJAAIAAgCIAEAAIAHAAIAAACIgCAAg");
	this.shape_6.setTransform(394.35,195.175);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(204,204,204,0.796)").s().p("AmbAyIAFgHIAGgHIAIgIIAJgGIAKgGIAQgJIADgBIAQgGIARgEQAXgHAXgEIACAAIABAAIAJgCIACgBIAAABIADgBIAAACIAAAAIgCAAIgBAAIABADIABAGIgiAGIgGABIgCAAIgBAAIgJACIgCAAIgWAHIgLAFIAIgDIAMgEIgBABIgOAEIgJAEIgBAAIgFADIgBAAIgCABIgBAAIgKAGIgCABIgJAGIgGAFIAMgKIAJgFIAIgEIgWACIgMAIIgIAIIAAABIgGAGIgEAGIgBABgAGOAjIhkgCIgZgDIjdgkQgRgEABAEIgegEIgcgFIgdgCIgDgBIAJgEIAUgJIgHgEIABAAIgDgCIAJAAIAPACIAKABQgEAAgBABIAJABIBRAIIA8ALICmAnIgSgGIBpAOIANABIABAAIgNAAIgBABgAl+AiIADgCIABgBIAGgDIgHAEIgEADIABgBgAEbARIhWgbQgjgKgdgHIghgHIghgGIhDgKIARABIBrAMQAbAEAZAHIAYAGIBNAUIARAGIAUAIIAOADIgDgBIAvAIQAAAAAAABQABAAgBAAQAAAAgBAAQgBgBgCAAIgKgBIAGABIgBAAIAFABgAEeATIgIgCIAFAAIAKADgAj2gFIAAABIgGAAIAGgBgAjzgIIAAgCIAAgDIAAgFIgFABIAAgCIAAgCIABAAIAEgBIANgDIAjgEIAGgBIAAABIACAEIAAABIgBACIAIAAIgCAEIAAABIAAABIgCAEIgFABIgBAAIgTADIgSACIgRACgAhAgNIgTgBIgFAAIgBAAIAEgDIACgCIADAAIAOAAIAMABIgDACIAQACIAEABIADABIgegBgAisgRIAAgBIABgFIAAgBIADAAIABAAIADAAIAAgFIAAgDIAEgBIAFAAIABAIIAHAAIAVAAIABAAIAMABIgNgHIgIgDIAJgBIADAAIAGAAIAKgBIATABIAXgBIgCACIgBABIgEADIgMALIgUgCIAEADIADAAIgUAAIADACIACACIgXAAIgKAAIgFgBIgEABIgKAAIAAAAIgJABIAAgEgAijgTIAAADIAKAAIAAgEIAHAAIABAAIgBgDIgDAAIgPAAIABAEgAg3gkIgJAAIABgBIACgBIAVADIgPgBg");
	this.shape_7.setTransform(401.525,195.525);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(204,204,204,0.796)").s().p("AnfA4IAFgIIAIgIIAJgJIALgHIALgHIAOgHIAFgDIADgBIATgGIAUgGQAcgIAdgFIALgCIABACIAAAGIgeAEIgBABIgNADIgOAEIgQADIgXAIIgCABIgBABIgNAFIABAAIgEACIgNAIIgEACIgCABIgCACIgBABIgIAGIAFgEIADgCIgDABIgGAGQAGgGAIgGIAJgFIABgBIAEgBIAFgDIgYAFIgOAJIgQARIgBABIgEAGIgBACgAFcAoIgegDIkBgrQgUgFABAFIgjgGIghgFIgigDIgPgCIgBAAIgQAFIgEgBIgMgDIgCgBIAJAAIgIgBIAEgDIgRAAIgLgEIgBAAIgKgFIgEAAIgKAAIAAABIABAAIAHAEIAFADIABABIAEADIACABIgUAAIgRgBIgPABIgGAAIAAgBIgCgEIAAgBIgBgEIAAgBIgCgHIANgBIAUgBIAWgBIAAAAIAKgBIALAAIAXAAIAYgBIAOgIIADACIAJAFIgVgBIAaAEIgSgBIgNgBIgHAFIgCABIgEADIgOAKIAHAAIAZABIAGAAIAJgDIAXgIIgIgEIABgBIgKgFIAWABIASACIAMABIgHACIAKABIBfAKIBHANICkAnIAIABIAOAFIBtAOIAPAAIABABgAFVAYIhwgiQgpgNgigHIgmgIIgmgHIhOgMIATACIB9AOQAfAGAdAHIAdAIIBaAYIATAGIAXAKIASAEIgEgCIA2AKIgEAAIgMgCIAGABIgBABIAHABgAmLAIIANgDIAAAAIgQAFQgHACgLAFIgBAAQAKgFAMgEgAkhgMIABgHIgBgEIgFABIAAgCIAFAAIA0gFIAAAAIAHAAIgCAGIAFAAIADgBIgDABIgFABIAAgBIgGABIAAAFIgGABIgWADIgYACgAkngLIADgBIAAABIgDAAgAjdgdIAGAAIAAADIAAAAIAAAGIgHABIABgKgAk0gYIADgBIAAACIgWADIATgEgAjXgiIAAgFIAHgBIABAAIACAIIgKABIAAgDg");
	this.shape_8.setTransform(408.65,195.875);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("rgba(204,204,204,0.796)").s().p("AojA/IAHgKIAIgJIALgKIAHgEIAIgGIABAAIgDACIgGAEIgSAPIgBABIgHAJIgBAAIgFAHIAAACgAHbA0IgCgBIhLgDIgigEIkmgyQgWgGABAGIgogHIgmgGQgagDgMAAIgTgCIgTgBIATgFIgaAAIgTAAIAIgFIgaAAIAKADIAGACIghAAIABAAIgJAAIgGAAIgCgBIgPAAIgGAAIgPABIgdACIgDgJIAAAAIAAgCIgGABIgJAAIAAgBIgBgHIAEAAIAFgBIAEAAIAPgBIAXgCIAYgBIgGADIABAAIAQAEIgCABIgEADIABAAIAEACIAUgBIgQgEIgDgBIAPgIIAJAAIANAAIAZAAIAdAAIgOAGIgBABIgGADIAAAAIgNAHIALABIAcABIAJAAIAFgBIAagHIgJgFIACAAIgOgGIgDgBIgPgCIAKAAIAmACIAVADIAOABQgGAAgDABIANACIBtANIBQAPIDKAxIgYgCIAKADICVATIASABgAoDAoIgCABIAIgGIACgBIANgKIALgFIACgBIAEgDIAMgEIgPAGIACAAIAbgLIAQgFIgBABIgTAGIgUAIIgDABIgCACIgQAIIgJAFIgMAKIACgCgAGRAgIANAEIgTgFIAGABIiLgrQgvgOgmgIIgsgJIgsgIIhZgNQAIAAAOACICPARQAjAGAhAIIAiAJIBmAcIAWAHIAaAMIAUAEIgEgBIA+ALQABAAAAAAQAAABAAAAQgBAAgBgBQgCAAgBAAIgHgBIgCABIAIABgAnxATIARgJIAGgDIADgCIAVgHIAYgHQAfgIAhgFIAMgDIAAABIABAEIgqAHIgaAHIgeAIIgWAKIgKAEIgEADIgWAFIAIgFgAnPAKQAUgJARgEIAUgGIAbgFIgTAEIgRAFIgTAFIgfALIACgBgAlQgSIABAAIABgCIAAgHIgFABIAAgEIAAgEIAEgBIABAEIAvgFIABACIgBAIIAGgBIgCAEIgEAAIgQACIggADIgBAAgAlggfIADgBIACAAIAAACIgBAAIgCAAIgXADQAKgCALgCgAkJgfIgGAAIAAgCIAGAAIAAACIAKgBIgKACIAAgBgAkXgkIABAAIAHgBIAAAEIgDAAIgDABIgCAAIAAgEg");
	this.shape_9.setTransform(415.7,196.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(204,204,204,0.796)").s().p("ApnBFIAIgKIAIgJIABgBIAMgLIgMALIgBABIgIAJIgBABIgGAJIgBABgAJUA9Ig+gBIgCAAIhVgEIgmgFIlKg5QgagHACAHIgtgIIgqgHIgrgFIgWgCIgWAAIglgDIgJgBIAMgGIAIACIAOAEIAEAAIAggGIgggBIgXAAIAKgFIANAAIAfACIAOABIAdgGIgKgEIABAAIgZgJIgCgBIAEABIAXABIgegEIgDgBIADAAIA0ADIAXADIARACQgIAAgCABIAOABIB6AQIBaARIDxA8IgpgEQADACAJACICoAVIAUABIgSAAIgBABgAHMAnIAFACIgIgCIADAAIimgyQg1gQgrgKIgxgKIgygIIhkgOQAJAAAQACIBYAIIACABIANACIAEAAIAFAAIAEABIBPAQIgKgFQAbAGAaAHIAlAKIB6AiIASAGIAeANIAWAEIgFgCIBGAOQABAAAAAAQABAAgBAAQgBAAgBAAQgBAAgDAAIgQgDIAJACIgCABIAIACgApEApIgDACIAJgHIASgMIAIgEIADgCIABAAIAEgBQAPgHASgGIARgFIgCABIgUAGIgXAJIgFACIgBAAIgSAKIgOAJIgJAHIACgCgApKAmIAFgEIAMgJIACAAIgFAEIgJAFIgFAEgAovAUIATgJIAGgEIAEgCIAYgIIAagIQAkgKAlgGIANgCIAAACIgvAIIgdAIIghAKIgZAKIgLAFIgJAGIgTAFIAIgFgAoZAOIAJgEIAGgDQAXgIAUgHIAWgGIAegGIgWAFIgSAFIgVAHQgXAGgRAHIgOAHIAFgDgAlQgfIAFgBIABAAIAEgBIgBADIAAAAIgGABIgEAAIgFABIglADQAPgBAcgFgAl8gfIgEABIgBgHIAAgEIAFgBIAAAEIArgEIABADIAAADIAHgBIgBACIAAAAIgGAAIgKABIgCAAIgBAAIAAAAIgNACIgSADgAk8gjIAJgCIAGgBIgGAAIAAgBIAAAAIAGAAIgBgCIAAgBIAAgDIgCgGIgBgDIAJgBIAbgBIAagCIAmgCQgLADgJADIABAAIAHABIAKADIgHADIgBAAIABAAIAIADIAFAAIAIgBIALABIgMgEIgNgCIAEgDIAPgGIAFgDIAHAAIAPABIAcABIAjgBIgYAKIgCABIgFACIgBAAIgKAEIgqAAIADAAQAKACAJADIgjAAIAEABIAGAEIgHgBIgegBIgdgBIgTgBIgQACIgNACIgIABIgHABIgCAAIAAgDgAmNgmIAEgBIABAAIACgBIABABIABACIgCAAIgCAAIAAAAIgCAAIgbAEIAYgFg");
	this.shape_10.setTransform(422.825,196.55);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("rgba(204,204,204,0.796)").s().p("AqsBMIAIgMIALgMIAFgEIgQARIgIAMgAHwA/IgqgGIlvhAQgcgHABAHIgxgJIgvgHIgxgGIgXgCIgZgBQgOAAgbgEIgXgBIAFgDIARgGIAJADIAPACIAGABIAqgGIgngCIgbAAIANgEIg8gBIANADIAPACIgnAAIgCAAIAKADQAKAFAKACIgPgBIghgBIghgCIgzAAIgTACIgBAAIAAAAIgDgGIAAgBIAAAAIgBgFIgCgDIgCgFIAdgDIAdgCIAegCIA6gDIADAAIgFABQgSADgOAFIgGACIABAAIAPACIgBABIgGADIABAAIADABIAPgBIAIAAIgQgDIgEgBIAOgFIAJgDIAPgFIACAAIAQAAQAZACAGgBIAiAAIAHACIgcAIIgFACIgCABIgGACIgBAAIgFACIANAAIAjABIAWABIAXgDIgMgEIABAAIgcgIIgGgCIgBAAIAJgEIABAAIACAAIgKgCIAOABIAvADIAZACIASACQgHABgDABIAQACICHASIBkATIEVBFIi+g5Qg7gRgwgLIg2gLIg3gKIhwgPQALAAASACIAyAGIABAAIAKACIAQADIAPAEIAQACIADAAIAGABIALABIBQARQgSgIgTgGIgHgCIANACIAkAHIANAEIAKADIAPAEIB9AnIBAAPIAPACIAGABIAgAPIAZAFIgFgCIBNAOQAEABgJgBIgNgBIAFAAIgCABIAJADIiVgRQADACAJACIC8AXIAWABIADABgAqNApIATgOIAFgCIgIAFIgPALIgIAHgApzAdIAPgJIADgCIAIgCQAQgJAUgHIASgEIAAAAIgYAHQgKAEgPAHIgFACIgBAAIgUALIgQAKIgEACIAPgKgAp6AhIAGgDIgKAHIAEgEgAprAXIAEgDIgOAFIAIgEIAUgLIAHgDIAEgCIAbgJIgZAKIgNAGIgOAIIAFgBIgDABIgPAKIAJgHgApFAFQAYgKAXgHIAYgHIAjgGIgaAFIgUAGIgYAGQgZAIgUAJIAJgEgAoLgRIAggIIAzgIIAAAAIgNACQgpAHgpALIgNAEIAZgIgAmDglIAFgBIgCADIgDAAIgkADIAkgFgAmrgkIAXgEIARgCIAHgBIgCAEIgDAAIgCAAIgZADIgPACgAmvgtIADAAIABAJIgEABIAAgKgAmrgkgAl5gqIgBgBIAGgBIAEAAIAAAEIAAABIgEAAIgDAAIgCAAgAm7gtIAEgBIAAACIgfAEIAbgFgAhthDIAAAAg");
	this.shape_11.setTransform(430.05,196.9208);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("rgba(204,204,204,0.796)").s().p("ArxBSIAKgNIAHgIIADgDIABgBIgEAEIgRAWgALWBOIi1gIQgUgCgagEImThHQgggIACAHIg2gKIg0gIIg1gGIgagCIgbgBIgtgFIgtgDIgkgCIgkgCQgsgBgbABIgYADIgCAAIgFAAIgEAAIgFABIgBAAIgBAAIAAgBIgDAAIgDABIAAgCIAGgBIgBgFIADAAIAAAEIAJgBIAAADIAHgBIAAgBIgBgCIAygJIg0AFIgFABIgBgGIAEgBIAAgBIgDgHIAvgFIAhgCIAggCIBBgDIAQgBIAIABIgFABIgDAAIgWAEIgOACIASAAIAAAAIAhABIAhABIgOACIgQACIg5AAIgQAAIgHABIgBAAIABAAIAQACIALABIgPACIgEAAIgBABIABAAIAGABIAVAFQALAFALACIAHgCIATgGIAMADIARACIAFABIA1gHIADAAIgygCIgcAAIAPgEIAAAAIAEgBIAIAAIAnABIAgADIAOgBIgNgEIABAAIgegIIgHgCIgBAAIAIgCIAAAAIAOgDIAAAAIAGgBIgYgDIAXABIAFACIAFABIAIgCIAbACIAcADIAUACQgJABgDABIASACICUAUIBvAWIEwBNIiAgnIBAAOIAlAEIgEgCIgfgKIA1AOIgSgCIAgAOIAbAGIgGgDIBVAQQAFACgLgCIgTgCIALACIgCABIAJACIijgTQADADALACIDOAZIAYABIADABIgYAAIgCABgArOArIAVgPIAHgDIAGgEIATgJIAEgCIAMgGIACgBQAPgGAPgGIApgOIAjgIIA4gKIACAAIAEgBIAAAEIgDAAIgCABIgOACQggAFggAIIgLADIgPAEIgCABIgCAAIgHACQgjAMgYALIgPAIIgFACIgPAJIAMgIIgJADIgKAGIgRAMIgOANgAq/AlIAGgEIgRANIALgJgAqyAdIAQgKIABAAIAJgEIABAAQASgKAXgHIAVgGIgCABIgZAIQgLADgRAIIgIADIgVALIgSAMIANgJgAnZgnIAAgDIAAgBIAcgFIAJgBIAAAIIgeACIASgDIgEABIgVACgAnog1IAEgBIAAACIAAAAIgiAFIAegGgAnigzIABgDIAEgBIAAACIgFACg");
	this.shape_12.setTransform(437.175,197.325);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("rgba(204,204,204,0.796)").s().p("As0BZIAGgHIgGAIgAMZBYIhSgCIgCgBIhxgGIgygHIm4hOQgjgJACAIIg6gLIg5gJIg6gGIgdgDIgdgCQgQAAghgEIgxgFIgngBIgngCQgwgCgeABIgcADIgNABIAAgDIAAgBIgDgFIgBgCIgBgFIgBgBIgEgIIBDgHIAjgDIAkgCIBGgDIASAAIAUABIACAAIgBAAIgDABIgCAAIgEAAIgMADIgCAAIgLACIgNACIgbAEIgSAFIACAAIAPABIAAAAIgHACIgDABIACAAIAdAHQAMADAMADIAHgDIAVgEIAPACIASACIAGAAIA5gFIATgCIATgBIACgBIgNgDIABAAQgRgEgQgDIgIgCIgCAAIAIgCIAAAAIAPgCIAGgBIAEAAIAAAAIACAAIAHgBIABAAIADgBIAGAAIABAAIAIgBIAFAAIAFAAIgFgBIgDAAIgCAAIADAAIgDAAIgBAAIgJABIgBABIgqgGQAmABAkADIAeADIAWADQgJAAgEACIAUACICiAXIB4AYIFNBUIhRgZIACAAIA4AHIAbAMIAeAGIgGgDIBdASQAFACgMgCIgVgDIAMACIgDACIALADIiygWQAEADALACID8AdIgYABIgCAAgAsqBMIAAAAIABAAIAHgIIgHAIIgBAAIgEAGgAseA/IABgBIgFAGgAsNAvIAWgRIALgEIAGgEIAWgNIAPgHQAQgHARgGIAsgQIAngJIA8gKIABAGIgOACQgxAJgxANIgiAKIgOAFIgXAIIgBABIgCABIgDACIgRAJIgGADIgEABIgQAKIgSAPIAMgKIARgNIgNAIIgSAOIgQANgArwAfIAMgIIAKgEIAHgEQAVgKAYgIIAXgHIgCABIgbAJIgfANIgPAGIgQAJIgUAMIgGAEIAUgNgAnlgwIAFgBIgBACIgEAAIgWACIAWgDgAnWgwIAAgCIABAAIAAACIAAAAIgBAAgAoTg6IACgBIAGgBIACgBIAAADIgBAAIgDAAIAAAAIgEAAIgjAGIAhgGgAnYhGIAGgCIACAAIACAIIgIABIgCgHgAkJhLIATgFIAZABQASAAASABIgPACQgKACgHAAIg2AAIAGgBg");
	this.shape_13.setTransform(444.175,197.55);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("rgba(204,204,204,0.796)").s().p("AsKBdIABgCIgBACgAsABPIABgBIABgCIAAABIgBABIgFAHgArzBAIACgBIgMAMgArhAvIAZgSIAHgDIAKgHIAZgPIAQgHQARgIASgHIAwgQIArgLIBAgLIAAABIABAIIgPADQg1AIg0AOIglALIgkANIgEACQAQgGATgGIAZgIIgCABIgeAKQgNAFgUAIIgTAJIgPAHIgVAOIgFADIAUgNIAJgHIgBABIgTALIgSAOIAJgHIgKAHIgSAQgAKyAjIAXADIBCATgAmpg5IAAABIgPABIAPgCgAmLg8IgDgEIgBgDIgBgCIgCgEICfgQQApgDAggBIAiABIgDAAIgOADIgYADIgEAAIAMAAIArAAQAIAAALgCIAQgCIgagCIAPAAIAGgBIAdAFIAbAEIgwAHIgCAAIgEABIhcAAIgVgBIgCAAIgLAAIgbABQgeABgbADIgpAGIgoAGIgKABIAAgBgAnShEIACgBIAAABIAAABIgmAFIAkgGg");
	this.shape_14.setTransform(440.325,198.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("rgba(204,204,204,0.796)").s().p("AtGBiIACgCIAJgOIAFgFIgEAFIgKAOIgCACgAsaAwIAbgUIACAAIAQgMIAagPIASgIQATgJATgHIA0gSIAtgLIBFgMIAAAAIAAACIACAKIgQACQg4AJg5AQIgYAHIgCAAIgOAFIgNAEIgeAMIgBAAIgCABIgBABIgBAAIgPAHIgTAKIgOAIIgJAFIAAABIgCABIgRAMIgSAQgAMAArIARACIA2AQgAnShBIAAABIgIAAIAIgBgAm5hHIgCgDQA+gJAygEIhDAMIgpAHgAn3hNIAMgDIgCADIgBAAIgBAAIgFABIgBgBIAAABIgoAGIAmgHgAAChSIgBgBIAAABIAAAAIgkgHIgKgBIAEgBIAAAAIAHABQAXABAaAEIAJADIAHACIgdgCgAjmhYIASgDIgKABIgNABIgrgBIgrAAIBbgGIBGAAIgLABIgNACIgPADIgRADIgOgBgAiOhhIASAAIgNAAIgDAAIgCAAg");
	this.shape_15.setTransform(446.6,198.7125);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("rgba(204,204,204,0.796)").s().p("An9ByIABgBIABgCIAKgOIACgBIANgQIACgBIATgTIAdgVIAGgDIABAAIAWgOIAVgLQAhgPAwgQIAjgKIAfgJIAlgIIgzAKIglAKQghAKglAQIgxAXIgeATIgXARIAPgMQAMgKASgLIAcgRIATgIQAUgKAUgIIA4gTIAxgMIBJgNIAAABIAAAAIAAABIAAABIACAKIABACIgRADQg9AKg9AQIgqANIgpAOIgHADIgKAFIgfAPIgWANIgUAPIgCABIgVASIgQASIgMAQIgBABgAhxg+IAAAAIgEAAIAEAAgAhchAIgBgBIA4gIIBGgNQg3AEhFALIgGABIgDgGIAAAAIgBAAIAAgBIAAgBIDQgVQAvgEAlAAIAuAAIAtACIgTADQgMACgJAAIhlAAIhhAGIAtABIAvABIANgBIAbgDIANAAIAYAAIgPACIgSACIgXACIgVgBIgiACQgiAAggAEIguAHIguAHIgkADIAAAAgAHLhnIgwgDIgngDIBIAEIAmAEIAcADIgFAAIgugFgAFxhpIgMgBIhDgHIA8ACIAWACIgUgBIA3AHIgmgCg");
	this.shape_16.setTransform(413.975,198.125);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("rgba(204,204,204,0.796)").s().p("AoeB4IACgDIAKgPIACgCIAOgQIACgCIAVgUIAQgMIAOgKIAHgEIAYgPIAXgMQAjgQAzgRQAWgIAPgDIAhgJIAogJIg3ALIgnAKQgkALgnARIg0AYIggAUIgZATIARgNIAfgXIAegRIAUgJQAWgLAVgIIA8gUIA0gNIBOgOIAAACIAAABIAAABIACAHIACAGIgSADQhCALhAARIguAOQgWAHgVAIIgHAEIgMAFIggAQIgYAOIgYARIgVATIgRATIgMAPIgCADgAh9hFIACAAIAAAAIgBAAIgBAAgAhuhHIgDAAIAAgBIgBgCIgBgCIASgDQBKgLA6gFIhLANIhFALgAHmhrIgzgFIgCAAIg6gHQAyACAwAEIApAEIAdADQgMABgEACIgpgEg");
	this.shape_17.setTransform(417.625,198.525);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("rgba(204,204,204,0.796)").s().p("AklBgIACgCIAPgRIACgCIAWgVIAKgHQAOgMAQgKIAZgPIAYgMQAmgTA2gSQAXgIAQgEIAjgJIAqgJIg6ALIgpALQgmAMgqASIg4AZIghAWIgaAUIARgPIAhgXIAggSIAVgLQAYgLAWgIIA/gWQAZgHAegHIBSgOIABAAIAAAAIAAACIAAACIAAABIABAEIACAFIAAgBIAAgCIgBgCIAAgCIgBgCIAAgDIABABIAAADIACADIAAgCIAAgBIAAAAIAAgBIAAgDIAAgBIABAAIAAABIAAADIAAABIAAABIAAACIABABIABABIAAACIAAABIAAABIABACIAAACIgXADQhFAMhEASIgxAPQgXAHgXAJQgBACgGACIgMAFIgjARIgYAPIgaASIgXAUIgSAUIgPATgABshJIgBgCIgBgCgACLhXIgBgCIgBgDIgBAAIAegGQBOgLA/gFIhQAOQg4AJggAEIACAAIgEAAIACAAg");
	this.shape_18.setTransform(394.3,199.975);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("rgba(204,204,204,0.796)").s().p("ASjCNIh7gFIgEAAIiogLQgigEgqgHIqTh6QgzgNACANIhXgSIhVgOQg6gIgegCIgrgEIgrgDQgZgBgxgHIhJgGIg6gCIg8gDQhHgEgtACIgqAFIggABIguACQgjADgoAHQhKALhJAUQghAJgRAHQgaAIgYAIIgIAFIgMAFIgkATQgNAGgOAJIgbATIgZAVIgTAVIgQAVIAPgVIABgBIAqgrIAigZIA/giQAcgLASgHIApgOIACgBIghAKQgmANgeAOIgjATQgOAIgPALIgKAHQAOgMAQgKIAbgQIAagOQAogSA5gUQAYgIASgEIAlgKIAsgKIg9AMQgUAFgYAHQgpAMgsATIg7AcIgjAWIgcAVIASgPQAPgLAVgOIAigTIAWgLQAZgMAYgJIBCgXQAbgIAggHIBmgSIAAABIAAABIgBAAIgEABIAAAAIgDAAIAAABIgBAAIAAAAIgCABIgBABIgDABIAAgBIAAABIAAAAIAAABIAAAAIAAABIABACIACACIAAgBIAAgBIgBgBIAAAAIACABIAAgCIABgBIAAACIABABIAAABIAAAAIAAABIABABIAAABIAAABIABACIABgCIABgDIABAAIABACIABACIABgCIABACIABABIATgIIAAgBIABABIAAABIAAAAIACABIABAAIAAABIABgBIAAAAIgDgBIgBgBIAAAAIABgBIAAgBIABABIABgBIgCAAIgBAAIAAgEIAAgBIgEABIAAgBIgCgCIgBACIAAABIAAABIAAAAIgCgBIgBAAIgBgBIgBgBIAAgBIAAAAIAAAAIgBAAIAAgBIgCAAIgBAAIAAgBIAygIQBTgNBCgFIhVAPQhAALgiADIBLgHIA4gIIA4gJQAngEAogBIApgCQgaAAgegBIg3gBIB1gHIB4gBQALAAAPgCIAXgDQgbgCgbAAIg2AAQguAAg4AFIknAeIgGAAQgcAFgdAEIAwgJQAYgGAYgEIAzgIQArgHA9gEIA1gEIA1gDIBqgDIAaAAIAeABQAuADAMgBQAvgBAwACIAuADIhCgIQA4ACA2AEIAuAFIAhAEQgPAAgEADIAdAEID0AlIC0AlIHzCBIlXhmQhqgdhWgTIhhgTIhjgQIjKgaQATgBAgAEIDKAXIB3ATQBQAQBKAUIBLAWIDnBCIAxAQIA7AaIAtAJIgJgDICKAbQAJACgSgCIgggEIASADIgEACIAQAEIkLghQAFAEASAEIF+AqIgoABIgDAAgANRBMIiMghIgXgFIhzgeIhqgbIgJgBIhJgSIhAgRIgbgGIgZgFIgugKQhGgNhOgMIgmgGIgJgBIgTgCIhXgKIg4gGIhJgGIhIgDIC5AVIAcAEIAcADIATADIAJACIAJABIBcARIACABIARAEIAcAHIAaAGIAaAFIAIABIAKABIARACICLAgQghgNglgLIgRgFIgmgJIgIgBIAnAFIAEABIAKACQAcAFAMADIAXAFIAKACIAbAHIASAFIAaAHIDbBAIBwAWQA1AIAnAEgAsahNIAAAAIAAAAIAAAAgAlchmIAcABIAZAAIAJAAIBVACIA9ACIgVgCIACAAIgNgBIADAAIASAAIAGAAIAHAAIgJgBIgJgBIAAAAIgDAAIgBAAIgBAAIgBAAIgPgBIgcgBIgYgDIgGAAIgCAAIgOgBIgCAAIgFAAIgBAAIgIgBIgBAAIgDAAIgDAAIgEAAIgEAAIgOgBIgKAAIgBAAIgDAAIgBAAIgIAAIgFAAIgCAAIgEAAIgDAAIgDAAIgFAAIgBAAIgCAAIgFAAIgEAAIgEAAIgDAAIgGAAIgRABIgJABIgQAAQgmACgeAEIACAAIAEAAIgFABIADAAIArgBIAhABIALAAIAfgBIAGAAgAsghSg");
	this.shape_19.setTransform(487.05,199.625);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("rgba(204,204,204,0.796)").s().p("ATmCaIiCgFIgDAAIiygMQgkgEgsgHIq4iBQg2gOADANIhcgTIhbgPIhbgLIgugEIgugCQgZgCg0gHIhOgHIg+gCIg+gDQhMgEguACIgtAFQgqAAgpADQgkAEgrAGQhOANhMAUQgkAKgSAHQgbAIgZAJQgCACgGADIgOAGIgmATQgNAHgPAJIgdAUIgZAXIgVAWIgQAWIACgEIANgSIACgCIAQgTIADgCIAYgYIAkgaIBDgkQAdgNATgGIAsgPIACgCIgkALQgnAOggAOIglAUQgPAJgQALIgTAPQATgQAWgOIAcgRIAbgPQAqgTA8gVQAagIATgFIAngKIAvgLIhBANQgVAFgZAIQgrAMgvAUIg+AdQgcARgJAHIgeAWIAUgQQAPgMAWgOQAVgNAPgIIAYgLQAZgNAagJIBGgZQAcgIAigHICmgdQBXgNBGgGIhaAQQhDALgkAEQAqgDAlgFIA7gJIA8gJQAogEArgBIArgCQgcAAgfgBIg6gBIB7gIIB/AAQAMAAAQgDIAYgDQgdgCgcAAIg6AAQgwAAg7AFIk4AgIgFAAQgfAGgfAEQAagGAagDQAZgGAagFIA1gJQAugGBAgFIA4gEIA4gDIBwgEIAcAAIAfACQAwADAMgBQBKgBBMAFIhGgIQBVADBQAJIAjAEQgQAAgFADIAgAFIEBAnIC+AnIIOCIIlphrQhwgfhbgUIhngUIhpgRIjUgbQAUgBAiAFIDVAXIB9AVQBVAQBOAWQApALAmAMIDzBGIA1ARIA+AcIAvAJIgKgEICTAdQAJACgTgCIghgEIASADIgEACIARAEIkagiQAGAEASAEIFlApIAqACIAEABIgpABIgDAAgAN8BXIiTgiIiSgmIkmhIQiHgeikgWQhQgLhIgGIhNgHIhOgEIDGAXIBiAPIBiARIBMAUIAcAFQAOADAXABICSAiQgjgOgogMQgngLgngGIA0AHIA5ALQAyAMA8AQIDnBDIB2AXQA5AJAoAEgAsrhYIggAHIAZgFIAKgCQABAAgBAAIgDAAgAiUhiIgWgCIAEAAIg3gEQgugDg7gCQhqgChGAIQAvgBAwAAQA1gBArABIBiADIBBADgAmvh/IgiAEIgQABIAvACICgACQBeACA9AFIgJgDIgNgDQgkgGgggBQgegCgkAAIiMgBIgEAAIgMAAgA0RCMIgCADIgBACgAn6iVICqgEIArACQAnACAuAFg");
	this.shape_20.setTransform(494.025,199.525);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1}]},5).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).wait(36));

	// PhotoMask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("Ag2A2QgXgWABggQgBgfAXgXQAXgWAfgBQAgABAWAWQAXAXABAfQgBAggXAWQgWAYggAAQgfAAgXgYg");
	var mask_graphics_5 = new cjs.Graphics().p("AjiDiQhdhdAAiFQAAiEBdheQBehdCEAAQCFAABeBdQBdBeAACEQAACFhdBdQheBeiFAAQiEAAheheg");
	var mask_graphics_6 = new cjs.Graphics().p("AkSETQhzhyAAihQAAigBzhyQBxhxChgBQCiABBxBxQByByABCgQgBChhyByQhxBxiiAAQihAAhxhxg");
	var mask_graphics_7 = new cjs.Graphics().p("AlEFCQiGiFAAi9QAAi8CGiHQCHiFC9AAQC+AACGCFQCHCHAAC8QAAC9iHCFQiGCHi+AAQi9AAiHiHg");
	var mask_graphics_8 = new cjs.Graphics().p("Al1FzQiaiZAAjaQAAjYCaibQCbiZDaAAQDbAACbCZQCbCbgBDYQABDaibCZQibCajbAAQjaAAibiag");
	var mask_graphics_9 = new cjs.Graphics().p("AmmGkQiviuAAj2QAAj1CviuQCwiuD2AAQD3AACwCuQCvCuAAD1QAAD2ivCuQiwCuj3AAQj2AAiwiug");
	var mask_graphics_10 = new cjs.Graphics().p("AnXHTQjDjBgBkSQABkSDDjCQDDjBEUAAQEUAADEDBQDEDCAAESQAAESjEDBQjEDDkUAAQkUAAjDjDg");
	var mask_graphics_11 = new cjs.Graphics().p("AoJIEQjXjWAAkuQAAkuDXjWQDZjVEwgBQExABDYDVQDYDWAAEuQAAEujYDWQjYDWkxAAQkwAAjZjWg");
	var mask_graphics_12 = new cjs.Graphics().p("Ao6I1QjrjqAAlLQAAlKDrjrQDtjpFNAAQFOAADsDpQDtDrAAFKQAAFLjtDqQjsDqlOAAQlNAAjtjqg");
	var mask_graphics_13 = new cjs.Graphics().p("ApqJlQkBj+AAlnQAAlmEBj/QEBj9FpAAQFrAAEAD9QEBD/AAFmQAAFnkBD+QkAD+lrAAQlpAAkBj+g");
	var mask_graphics_14 = new cjs.Graphics().p("AqcKVQkUkRgBmEQABmDEUkSQEWkSGGAAQGHAAEWESQEUESAAGDQAAGEkUERQkWETmHAAQmGAAkWkTg");
	var mask_graphics_15 = new cjs.Graphics().p("ArNLGQkokmAAmgQAAmfEokmQEqkmGjAAQGkAAEpEmQEpEmAAGfQAAGgkpEmQkpEmmkAAQmjAAkqkmg");
	var mask_graphics_16 = new cjs.Graphics().p("Ar+L2Qk9k6AAm8QAAm7E9k7QE+k6HAAAQHBAAE+E6QE9E7AAG7QAAG8k9E6Qk+E7nBAAQnAAAk+k7g");
	var mask_graphics_17 = new cjs.Graphics().p("AsvMmQlSlNAAnZQAAnYFSlOQFTlOHcAAQHeAAFSFOQFSFOAAHYQAAHZlSFNQlSFPneAAQncAAlTlPg");
	var mask_graphics_18 = new cjs.Graphics().p("AtgNXQlmliAAn1QAAn0FmliQFmljH6AAQH7AAFmFjQFmFiAAH0QAAH1lmFiQlmFin7AAQn6AAlmlig");
	var mask_graphics_19 = new cjs.Graphics().p("AuROHQl6l2AAoRQAAoQF6l3QF7l2IWAAQIYAAF6F2QF6F3AAIQQAAIRl6F2Ql6F3oYAAQoWAAl7l3g");
	var mask_graphics_20 = new cjs.Graphics().p("AvDO3QmOmKAAotQAAotGOmLQGQmJIzAAQI0AAGPGJQGPGLAAItQAAItmPGKQmPGLo0AAQozAAmQmLg");
	var mask_graphics_21 = new cjs.Graphics().p("AvzPoQmkmeAApKQAApJGkmfQGjmeJQAAQJRAAGjGeQGjGfAAJJQAAJKmjGeQmjGfpRAAQpQAAmjmfg");
	var mask_graphics_22 = new cjs.Graphics().p("AwlQYQm3mxAApnQAAplG3mzQG5myJsAAQJuAAG3GyQG4GzAAJlQAAJnm4GxQm3GzpuAAQpsAAm5mzg");
	var mask_graphics_23 = new cjs.Graphics().p("AxWRJQnMnGABqDQgBqCHMnGQHNnHKJAAQKLAAHMHHQHMHGAAKCQAAKDnMHGQnMHGqLAAQqJAAnNnGg");
	var mask_graphics_24 = new cjs.Graphics().p("AyHR5QngnaAAqfQAAqeHgnbQHhnaKmAAQKoAAHfHaQHhHbAAKeQAAKfnhHaQnfHbqoAAQqmAAnhnbg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:284.75,y:23.8}).wait(5).to({graphics:mask_graphics_5,x:148.4,y:132.1}).wait(1).to({graphics:mask_graphics_6,x:148.4,y:132.1}).wait(1).to({graphics:mask_graphics_7,x:148.4,y:132.1}).wait(1).to({graphics:mask_graphics_8,x:148.4,y:132.075}).wait(1).to({graphics:mask_graphics_9,x:148.4,y:132.075}).wait(1).to({graphics:mask_graphics_10,x:148.4,y:132.1}).wait(1).to({graphics:mask_graphics_11,x:148.4,y:132.1}).wait(1).to({graphics:mask_graphics_12,x:148.4,y:132.1}).wait(1).to({graphics:mask_graphics_13,x:148.4,y:132.075}).wait(1).to({graphics:mask_graphics_14,x:148.4,y:132.075}).wait(1).to({graphics:mask_graphics_15,x:148.4,y:132.075}).wait(1).to({graphics:mask_graphics_16,x:148.4,y:132.075}).wait(1).to({graphics:mask_graphics_17,x:148.4,y:132.05}).wait(1).to({graphics:mask_graphics_18,x:148.4,y:132.05}).wait(1).to({graphics:mask_graphics_19,x:148.4,y:132.05}).wait(1).to({graphics:mask_graphics_20,x:148.4,y:132.075}).wait(1).to({graphics:mask_graphics_21,x:148.4,y:132.075}).wait(1).to({graphics:mask_graphics_22,x:148.4,y:132.05}).wait(1).to({graphics:mask_graphics_23,x:148.4,y:132.05}).wait(1).to({graphics:mask_graphics_24,x:148.4,y:132.05}).wait(36));

	// Photo
	this.instance_5 = new lib.photo_20210215_200610();
	this.instance_5.setTransform(40,40,0.5,0.5);

	this.instance_6 = new lib.PhotoAnimation("synched",0);
	this.instance_6.setTransform(140,140,1,1,0,0,0,100,100);

	var maskedShapeInstanceList = [this.instance_5,this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_5}]}).to({state:[{t:this.instance_6}]},59).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(342.9,250,977.1,170);
// library properties:
lib.properties = {
	id: 'F03CE29ED1ADFB428A029FC59A7B0AC9',
	width: 747,
	height: 420,
	fps: 30,
	color: "#252525",
	opacity: 1.00,
	manifest: [
		{src:"images/KaitlinCallingCard_atlas_1.png", id:"KaitlinCallingCard_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['F03CE29ED1ADFB428A029FC59A7B0AC9'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;